// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("backend.Models.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPFDevedor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Juros")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Multa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDevedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dividas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPFDevedor = "123456",
                            Juros = 1m,
                            Multa = 2m,
                            NomeDevedor = "José",
                            Numero = 1010
                        },
                        new
                        {
                            Id = 2,
                            CPFDevedor = "123777",
                            Juros = 2m,
                            Multa = 4m,
                            NomeDevedor = "João",
                            Numero = 1011
                        });
                });

            modelBuilder.Entity("backend.Models.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DividaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DividaId");

                    b.ToTable("Parcelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataVencimento = new DateTime(2020, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 1,
                            Numero = 1,
                            Valor = 100m
                        },
                        new
                        {
                            Id = 2,
                            DataVencimento = new DateTime(2020, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 1,
                            Numero = 2,
                            Valor = 100m
                        },
                        new
                        {
                            Id = 3,
                            DataVencimento = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 2,
                            Numero = 3,
                            Valor = 200m
                        },
                        new
                        {
                            Id = 4,
                            DataVencimento = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 2,
                            Numero = 4,
                            Valor = 200m
                        });
                });

            modelBuilder.Entity("backend.Models.Parcela", b =>
                {
                    b.HasOne("backend.Models.Divida", "Divida")
                        .WithMany("Parcelas")
                        .HasForeignKey("DividaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
